services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8080:8080
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://dock-host-ip:8080 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1024M
    env_file:
      - .env
networks: {}
