services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    volumes:
      - ${MEALIE_DATA}:/app/data/
    ports:
      - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - .env
x-dockge:
  urls:
    - https://mealie.lan.domain.com
    - https://mealie.domain.com
networks: {}
