services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG_PATH}:/config
      - ${TRANSCODE_PATH}:/transcode
      - ${MEDIA_PATH}:/data
        #    runtime: nvidia
        #    deploy:
        #      resources:
        #        reservations:
        #          devices:
        #            - capabilities:
        #                - gpu
    env_file:
      - .env
networks: {}
