services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}:/config
    #      - /etc/localtime:/etc/localtime:ro
    #      - /run/dbus:/run/dbus:ro
    #    privileged: true
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 4G
    env_file:
      - .env
networks: {}
