services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${DATA_PATH}:/var/lib/pgadmin
        #      - ${CONFIG_PATH}:/pgadmin4/config_local.py # optional for SSO and other configs
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - .env
networks: {}
