services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${CONFIG_PATH}:/app/data/configs
      - ${ICON_PATH}:/app/public/icons
      - ${DATA_PATH}:/data
    ports:
      - 7575:7575
    deploy:
      resources:
        limits:
          memory: 768M
    env_file:
      - .env
networks: {}
