services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    ports:
      - 2283:2283
    volumes:
      - ${UPLOAD_PATH}:/data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - utility
                - video
    healthcheck:
      disable: false
    env_file:
      - .env
  immich-ml:
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    container_name: immich-ml
    restart: unless-stopped
    volumes:
      - ${CACHE_PATH}:/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - utility
                - video
    healthcheck:
      disable: false
    env_file:
      - .env
networks: {}
