services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ${DB_PATH}:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh
        mongodb://localhost:27017/healthcheck
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
networks: {}
