services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    restart: unless-stopped
    privileged: true
    volumes:
      - ${DATA_PATH}:/opt
      - ${PROFILE_PATH}:/profiles
    #      - /dev/input:/dev/input #optional
    #      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 8443:443
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    env_file:
      - .env
networks: {}
