services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    deploy:
      resources:
        limits:
          memory: 256M
    env_file:
      - .env
networks: {}
