services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ${DB_PATH}:/var/lib/mysql
      - ${DATA_PATH}:/etc/mysql/conf.d/
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - --connect
        - --innodb_initialized
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    user: 3999:3999
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ${PMA_THEMES}/boodark-nord:/var/www/html/themes/boodark-nord
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
networks: {}
x-dockge:
  urls:
    - https://phpmyadmin.domain.co
