services:
  redis:
    image: docker.io/library/redis:latest
    container_name: redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ${DATA_PATH}:/data
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - .env
networks: {}
